# ワークフローの名前
name: Go CI/CD

# トリガーの設定
# リポジトリへのpushとpull_requestをトリガーとする
on:
  push:
  pull_request:

# ジョブの設定
jobs:
  # テストジョブ
  test:
    # ジョブの名前
    name: Test
    # ジョブの実行環境
    runs-on: ubuntu-latest
    # ジョブのステップ
    steps:
      # ソースコードの取得
      - name: Checkout
        uses: actions/checkout@v4
      # Goのインストール
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.7
      # テストの実行
      - name: Run tests
        run: go test -v ./...

  # CDジョブ
  build:
    # ジョブの名前
    name: CD
    # ジョブの実行環境
    runs-on: ubuntu-latest
    # ジョブのステップ
    steps:
      # ソースコードの取得
      - name: Checkout
        uses: actions/checkout@v4
      # Goのインストール
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.7
      # ビルド
      - name: Build
        run: go build .
      # デプロイ
      - name: Deploy
        run: |
          echo "$FIAP_KEY" > fiap_key.pem
          chmod 600 fiap_key.pem
          scp -i fiap_key.pem ./go-fiap-client azureuser@fiap.eastus.cloudapp.azure.com:/home/azureuser
        env:
          FIAP_KEY: ${{ secrets.FIAP_KEY }}
