# ワークフローの名前
name: Go CI

# トリガーの設定
# リポジトリへのpushとpull_requestをトリガーとする
on:
  push:
  pull_request:

# ジョブの設定
jobs:
  # テストジョブ
  test:
    # ジョブの名前
    name: Test
    # ジョブの実行環境
    runs-on: ubuntu-latest
    # ジョブのステップ
    steps:
      # ソースコードの取得
      - name: Checkout
        uses: actions/checkout@v4
      # Goのインストール
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.7
      # テストの実行
      - name: Run tests
        run: go test -v ./pkg/fiap/...