# ワークフローの名前
name: Go CI/CD

# リポジトリへのpushとpull_requestをトリガーとして設定
on:
  push:
  pull_request:

# ジョブの設定
jobs:
  # テストジョブ
  test:
    # ジョブの名前
    name: Test
    # ジョブの実行環境
    runs-on: ubuntu-latest
    # ジョブのステップ
    steps:
      # ソースコードの取得
      - name: Checkout
        uses: actions/checkout@v4
      # Goのインストール
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.7
      # テストの実行
      - name: Run tests
        run: go test -v ./...

  # ビルドジョブ
  build:
    # ジョブの名前
    name: Build
    # ジョブの実行環境
    runs-on: ubuntu-latest
    # ジョブのステップ
    steps:
      # ソースコードの取得
      - name: Checkout
        uses: actions/checkout@v4
      # Goのインストール
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.7
      # ビルド
      - name: Build
        run: go build .
      # artifactの作成
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-fiap-client
          path: ./go-fiap-client

  # デプロイジョブ
  # 以下の部分は結合テストやパフォーマンステストに使用したため、コメントアウトしました。
  # deploy:
  #   # ジョブの名前
  #   name: Deploy
  #   needs: [test, build]
  #   # ジョブの実行環境
  #   runs-on: ubuntu-latest
  #   # ジョブのステップ
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # Goのインストール
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: 1.21.7
  #     # artifactのダウンロード
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: go-fiap-client
  #         path: ./go-fiap-client
  #     # scpでサーバーにデプロイ
  #     - name: Deploy
  #       uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.FIAP_KEY }}
  #         port: ${{ secrets.PORT }}
  #         source: "./go-fiap-client"
  #         target: "/home/azureuser"